config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/:id' => 'users#show'   #MypageへのRouting
  resource :products, only: [:create, :new, :update]
  get 'products/popular_products' => 'products#popular_products'
  get 'products/fresh_products' => 'products#fresh_products'
  get 'products/:id' => 'products#show'
  get 'products/:id/edit' => 'products#edit'
  delete 'products/:id/destroy' => 'products#destroy'
  patch 'products/:id/update' => 'products#update'
  post 'reviews/create/:product_id' => 'reviews#create'
  delete 'reviews/destroy/:review_id' => 'reviews#destroy'
  
  resource :top, only: [:index, :show]
  root to: 'top#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
	# association
	belongs_to :user
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	# association
	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # association
  has_many :products
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :search

	def new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		product = Product.find(params[:id])
		product.source_code = params[:source_code]
		product.product_name = params[:product_name]
		product.save
	end

	def create
		Product.create(
			product_name: product_params[:product_name],
			source_code: product_params[:source_code],
			user_id: current_user.id,
			ave_rate: 0)
	end

	def destroy
		if Product.find(params[:id]).user_id == current_user.id
			product = Product.find(params[:id])
			product.destroy
		end
	end

	def show
		@product = Product.find(params[:id])
		@reviews = @product.reviews
	end

	def popular_products
		@products = Product.all.order("ave_rate DESC").page(params[:page]).per(2)
	end

	def fresh_products
		@products = Product.all.order("updated_at DESC").page(params[:page]).per(2)
	end

	def user_products(user_id)
		return Product.find_by(product_id: params[id]).page(params[:page]).per(2)
	end

	private
	def product_params
		params.permit(:source_code, :product_name)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def show
	end

	def create
		Review.create(
			rate: params[:rate],
			review: params[:review_text],
			user_id: current_user.id,
			product_id: params[:product_id]
		)
		product = Product.find(params[:product_id])
		sum = 0.0
		product.reviews.each do |review|
			sum += review.rate
		end
		ave = sum/product.reviews.count
		product.ave_rate = ave
		product.save
	end

	def edit
	end

	def update
	end

	def destroy
		if Review.find(params[:review_id]).user_id == current_user.id
			review = Review.find(params[:review_id])
			review.destroy
		end
	end

	def product_reviews(product_id)
	end

	def user_reviews(user_id)
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def index
		unless user_signed_in?
			redirect_to :new_user_session
		end
		@popular_products = Product.order("ave_rate DESC").limit(4)
		@fresh_products = Product.order("updated_at DESC").limit(4)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@show_user = User.find_by(id: params[:id])
		@user_products = @show_user.products.order("updated_at DESC").page(params[:page]).per(2)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_footer.html.erb
<nav id="tf-footer">
    <div class="container">
         <div class="pull-left">
         	<p>2016 © developed by Takuto Oooka</p>
        </div>
        <div class="pull-right"> 
            <ul class="social-media list-inline">
                <li>Koken wiki</li>
                <li>Koken home page</li>
            </ul>
        </div>
    </div>
</nav>

app/views/common/_header.html.erb
<% if user_signed_in? %>

<div id="tf-home">
  <div class="overlay">
    <div id="sticky-anchor"></div>
      <nav id="tf-menu" class="navbar navbar-default navbar-fixed-top">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to 'PContest', root_path, class: 'navbar-brand logo' %>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to 'HOME', root_path %></li>
                  <li><a href='/users/<%=current_user.id%>'>マイページ</a></li>
                  <li><%= link_to 'ログアウト', '/users/sign_out', method: :delete %></li>
                  <li><%= link_to '作品の投稿', new_products_path %></li>
                </ul>
              </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
      </nav>


      <div class="container">
          <div class="content">
              <h1>Processing Contest Web</h1>
              <h3>あなたの作品を投稿しましょう！</h3>
          </div>
      </div>
  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pcontest</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'animate.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'user_e.css', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'processing.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modernizr.custom', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'main', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'SmoothScroll', 'data-turbolinks-track' => true %>

  <!-- make views -->
  <style type="text/css">
  @media ( min-width: 768px ) {
    #banner {
      min-height: 300px;
      border-bottom: none;
    }
    .bs-docs-section {
      margin-top: 8em;
    }
    .bs-component {
      position: relative;
    }
    .bs-component .modal {
      position: relative;
      top: auto;
      right: auto;
      left: auto;
      bottom: auto;
      z-index: 1;
      display: block;
    }
    .bs-component .modal-dialog {
      width: 90%;
    }
    .bs-component .popover {
      position: relative;
      display: inline-block;
      width: 220px;
      margin: 20px;
    }
    .nav-tabs {
      margin-bottom: 15px;
    }
    .progress {
      margin-bottom: 10px;
    }
  }
  </style>

  <script type="text/javascript">
    $('.bs-component [data-toggle="popover"]').popover();
    $('.bs-component [data-toggle="tooltip"]').tooltip();
  </script>

  <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- make views -->

  <%= csrf_meta_tags %>

  <script type="text/javascript">
    var Pjs = new Array(8);

    function stop(num){ // not work
      if (Pjs[num]) Pjs[num].exit();
    }

    function run(num){
      stop(num);
      var canvas = document.getElementById('canvas'+String(num));
      var code = document.getElementsByName('source_code')[num].value;
      try{
        Pjs[num] = new Processing(canvas, code);
      }catch(e){
        alert(e);
      }
    }

    function runByCanvasText(num){
      stop(num);
      var canvas = document.getElementById('canvas'+String(num));
      var code = canvas.textContent;
      try{
        Pjs[num] = new Processing(canvas, code);
      }catch(e){
        alert(e);
      }
    }
  </script>
</head>

<body>
  <%= render partial: 'common/header' %>
  <!--<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  -->

<%= yield %>

  <%= render partial: 'common/footer' %>

</body>
</html>

app/views/products/_development.html.erb
<%
	if controller.action_name == "edit"
		product_name = @product.product_name
	    source_code = @product.source_code
	elsif controller.action_name == "new"
		product_name = "ProductName"
		source_code = ""
	end
 %>

<div class="space"></div>
<div class="container">
	<div class="row toppadding">
	    <div class="col-md-12">
			<input placeholder=<%=product_name%> type="text" name="product_name">
	    </div>
	</div>
	<div class="row toppadding">
		<div class="col-md-6">
			<canvas id="canvas0" width="320px" height="320px"></canvas> 
		</div>
		<div class="col-md-6">
			<textarea id="editor" rows=25 cols=80 name="source_code"><%= source_code %></textarea><br>
		</div>
	</div>
	<div class="row toppadding"">
		<div class="col-md-4">
			<%= button_tag type: 'button', onclick: "run(0)", class: "btn btn-primary my-btn dark" do %>Run<% end %>
		</div>
		<div class="col-md-4">
			<%= button_tag type: 'button', onclick: "stop(0)", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
		</div>
		<div class="col-md-4">
			<input type="submit" value="投稿する" class="btn btn-primary my-btn dark">
		</div>
	</div>
</div>

app/views/products/_products.html.erb
<% i = 0 %>
<div class="space"></div>
<% @products.each do |product| %>
	<div class="row toppadding">
        <div class="col-md-12">
            <a href="/products/<%=product.id%>">
				<canvas id="canvas<%=i%>" width="320px" height="320px"">
				<%=product.source_code%>
				</canvas>
			</a>
			<%= button_tag type: 'button', onclick: "runByCanvasText(#{i})", class: "btn btn-primary my-btn dark" do %>Run<% end %>
			<%= button_tag type: 'button', onclick: "stop(#{i})", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
        </div>
		<% i += 1 %>
    </div>
<% end %>
<%= paginate(@products) %>

app/views/products/create.html.erb
<div>
	<h3>投稿が完了しました</h3>
	<%= link_to 'HOMEへ戻る', root_path, method: :get, class: "btn btn-info" %>
</div>

app/views/products/destroy.html.erb
<div>
	<p>作品を削除しました</p>
	<%= link_to 'HOMEへ戻る', root_path, method: :get %>
</div>

app/views/products/edit.html.erb
<%= form_tag('/products/'+@product.id.to_s(10)+'/update', method: :patch) do %>
	<div class="space"></div>
	<div class="container">
		<h3>編集する</h3>
	    <%= render partial: 'development' %>
    </div>
<% end %>

app/views/products/fresh_products.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
            <h3>新しい作品</h3>
        </div>
        <%= render partial: 'products' %>
    </div>
</div>

app/views/products/new.html.erb
<%= form_tag('/products', method: :post) do %>
	<div class="space"></div>
	<div class="container">
		<h3>作品を投稿する</h3>
	    <%= render partial: 'development' %>
    </div>
<% end %>

app/views/products/popular_products.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
            <h3>人気作品</h3>
        </div>
        <%= render partial: 'products' %>
    </div>
</div>

app/views/products/show.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
            <h3><%= @product.product_name %></h3>
        </div>

        <div class="space"></div>
		<div class="row toppadding">
            <div class="col-md-12">
				<canvas id="canvas0" width="320px" height="320px"">
				<%=@product.source_code%>
				</canvas>
				<%= button_tag type: 'button', onclick: "runByCanvasText(0)", class: "btn btn-primary my-btn dark" do %>Run<% end %>
				<%= button_tag type: 'button', onclick: "stop(0)", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
            </div>
        </div>

		<% if current_user.id == @product.user.id %>
	        <div style="text-align:center;">
		        <div class="btn-group"  role="group">
		          <%= link_to '編集する', '/products/'+@product.id.to_s(10)+'/edit', class: "btn btn-info", method: :get %>
		          <%= link_to 'この作品を削除する', '/products/'+@product.id.to_s(10)+'/destroy', class: "btn btn-danger", method: :delete %>
		        </div>
	      	</div>
		<% end %>

		<div class="row toppadding">
            <div class="col-md-12">
            	<h3>この作品に対するレビュー</h3>

            	<div class="toppadding">
	            	<% @reviews.each do |review| %>
	            		<h4>コメント:<%=review[:review]%></h4>
	            		<h4>評価:<%=review[:rate]%></h4>
	            	<% end %>
            	</div>
            </div>
        </div>

        <% my_review_for_product = current_user.reviews.find_by(product_id: @product.id) %>

		<% if my_review_for_product %>
        <div class="row toppadding">
            <div class="col-md-12">
            	<h3>自分のレビュー</h3>

            	<div class="toppadding">
	            	<h4>コメント：<%=my_review_for_product[:review]%></h4>
	            	<h4>評価：<%=my_review_for_product[:rate]%></h4>
		          	<%= link_to '自分の評価を削除する', 
		          	'/reviews/destroy/'+my_review_for_product.id.to_s(10), class: "btn btn-danger", method: :delete %>
            	</div>
            </div>
        </div> 
        <% end %> 

	    <% unless my_review_for_product %>
			<%= form_tag('/reviews/create/'+@product.id.to_s(10), method: :post) do %>
				<div class="row toppadding">
		            <div class="col-md-12">
					    <h3>評価する</h3>
					    <p>
					    	<div class="space"></div>
					    	<h5>評価</h5>
							<select name="rate">
								<option value="nothing"> --- 評価を選んでください ---</option>
								<option value="1">よくないね・・・</option>
								<option value="2">あまりよくないね</option>
								<option value="3">普通</option>
								<option value="4">いいね！</option>
								<option value="5">とてもいい！</option>
							</select>
						</p>
					    <textarea id="editor" rows=3 cols=20 name="review_text" placeholder="一口コメント"></textarea>
		            </div>
		        </div>

		        <div class="row toppadding">
		        	<div class="col-md-12">
					    <input type="submit" value="SENT" class="btn btn-primary">   
		        	</div>
		        </div>
			<% end %>
		<% end %>

    </div>
</div>

app/views/products/update.html.erb
<div>
	<div>更新完了しました</div>
	<%= link_to 'TOPへ戻る', root_path %>
</div>

app/views/reviews/create.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="space"></div>
		<div class="row toppadding">
            <div class="col-md-12">
                <h2>コメントを投稿しました</h2>
				<%= link_to 'TOPへ戻る', root_path %>
            </div>
        </div>
    </div>
</div>

app/views/reviews/delete.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="space"></div>
		<div class="row toppadding">
            <div class="col-md-12">
                <h2>レビューを削除しました</h2>
				<%= link_to 'TOPへ戻る', root_path, class: "btn btn-info" %>
            </div>
        </div>
    </div>
</div>

app/views/reviews/destroy.html.erb
<div id="tf-portfolio">
    <div class="container">
        <div class="space"></div>
		<div class="row toppadding">
            <div class="col-md-12">
                <h2>レビューを削除しました</h2>
				<%= link_to 'TOPへ戻る', root_path %>
            </div>
        </div>
    </div>
</div>

app/views/top/index.html.erb
<% i = 0 %>
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
            <h3>人気作品</h3>
        </div>

        <div class="space"></div>
        <% i = 0 %>
        <% @popular_products.each do |product| %>
			<div class="row toppadding">
	            <div class="col-md-12">
		            <a href="/products/<%=product.id%>">
						<canvas id="canvas<%=i%>" width="320px" height="320px"">
						<%=product.source_code%>
						</canvas>
					</a>
					<%= button_tag type: 'button', onclick: "runByCanvasText(#{i})", class: "btn btn-primary my-btn dark" do %>Run<% end %>
					<%= button_tag type: 'button', onclick: "stop(#{i})", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
	            </div>
				<% i += 1 %>
	        </div>
		<% end %>

		<div class="row toppadding">
        	<div class="col-md-16">
        		<%= link_to 'もっと見る', '/products/fresh_products', class: "btn btn-primary my-btn dark", method: :get %>
        	</div>
        </div>
    </div>
</div>

<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
            <h3>新着作品</h3>
        </div>

        <div class="space"></div>
        <% @fresh_products.each do |product| %>
			<div class="row toppadding">
	            <div class="col-md-12">
		            <a href="/products/<%=product.id%>">
						<canvas id="canvas<%=i%>" width="320px" height="320px"">
						<%=product.source_code%>
						</canvas>
					</a>
					<%= button_tag type: 'button', onclick: "runByCanvasText(#{i})", class: "btn btn-primary my-btn dark" do %>Run<% end %>
					<%= button_tag type: 'button', onclick: "stop(#{i})", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
	            </div>
				<% i += 1 %>
	        </div>
		<% end %>

        <div class="row toppadding">
        	<div class="col-md-16">
        		<%= link_to 'もっと見る', '/products/fresh_products', class: "btn btn-primary my-btn dark", method: :get %>

        	</div>
        </div>

    </div>
</div>

app/views/users/_showproducts.html.erb
<% i = 0 %>
<div class="space"></div>
<% @user_products.each do |product| %>
	<div class="row toppadding">
        <div class="col-md-12">
            <a href="/products/<%=product.id%>">
				<canvas id="canvas<%=i%>" width="320px" height="320px"">
				<%=product.source_code%>
				</canvas>
			</a>
			<%= button_tag type: 'button', onclick: "runByCanvasText(#{i})", class: "btn btn-primary my-btn dark" do %>Run<% end %>
			<%= button_tag type: 'button', onclick: "stop(#{i})", class: "btn btn-primary my-btn dark" do %>Stop<% end %>
        </div>
		<% i += 1 %>
    </div>
<% end %>

app/views/users/show.html.erb
<% if @show_user.id == current_user.id %>
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
        	<h2>MyPage</h2>
        </div>

        <div class="row toppadding">
	        <div class="col-md-12">
		        <h4>NickName: <%= @show_user.nickname %></h4>
				<h4>Email: <%= @show_user.email %></h4>
				<%= link_to 'プロフィールの編集', edit_user_registration_path, class: "btn btn-info" %>
	        </div>
	    </div>

	    <div class="space"></div>
	    <div class="row top padding">
	    	<div class="col-md-12">
				<h2>My Products</h2>
				<%= render partial: 'showproducts' %>
				<%= paginate(@user_products) %>
			</div>
	    </div>
    </div>
</div>
<% else %>
<div id="tf-portfolio">
    <div class="container">
        <div class="section-title">
        	<h1><%= @show_user.nickname %>'s Page</h1>
        </div>

        <div class="row toppadding">
	        <div class="col-md-12">
		        <p>NickName: <%= @show_user.nickname %></p>
	        </div>
	    </div>

	    <div class="row top padding">
	    	<div class="col-md-12">
				<h2><%= @show_user.nickname %>'s Products</h2>
				<%= render partial: 'showproducts' %>
				<%= paginate(@user_products) %>
			</div>
	    </div>
    </div>
</div>

<% end %>